import { posts, type Post } from "@/lib/blog-posts";
import type { Locale } from "@/lib/i18n";

function sourcePost(index: number): Post {
  const post = posts[index];
  if (!post) throw new Error(`Missing source article ${index}`);
  return post;
}

const fr: Post[] = [
  { ...sourcePost(0), title: "Des stratégies de transformation numérique qui produisent des résultats", excerpt: "La transformation dépend moins des outils que des priorités. Voici comment choisir les bons objectifs et montrer rapidement les progrès.", category: "Stratégie", readTime: "5 min de lecture", imageAlt: "Une équipe planifie une feuille de route de transformation numérique", body: [{ type: "p", text: "Les programmes réussis commencent par une courte liste de problèmes métier, et non par une longue liste d’outils. Définissez d’abord les résultats attendus." }, { type: "h2", text: "Commencer par un processus" }, { type: "p", text: "Choisissez un processus douloureux, visible et mesurable. Concevez ensuite la version numérique la plus simple qui supprime le principal frein." }, { type: "quote", text: "La meilleure feuille de route est celle que les équipes voient avancer toutes les deux semaines." }, { type: "h2", text: "Rendre les progrès visibles" }, { type: "ul", items: ["Livrer de petits incréments utiles.", "Présenter le logiciel aux utilisateurs à chaque étape.", "Partager les mêmes priorités entre métier et technique.", "Mesurer l’adoption, pas seulement la livraison."] }] },
  { ...sourcePost(1), title: "Faire grandir une équipe agile sans la ralentir", excerpt: "Ajouter des personnes n’ajoute pas automatiquement de la vitesse. Ces pratiques préservent l’élan des équipes en croissance.", category: "Agile", readTime: "4 min de lecture", imageAlt: "Une équipe agile examine les tâches d’un sprint", body: [{ type: "p", text: "Les petites équipes avancent vite car la communication est simple. En grandissant, la coordination devient le vrai travail." }, { type: "h2", text: "Garder des équipes petites et autonomes" }, { type: "p", text: "Créez plusieurs petites équipes responsables chacune d’une partie claire du produit." }, { type: "quote", text: "Augmentez le nombre d’équipes, pas la taille de chacune." }, { type: "ul", items: ["Une vision produit commune.", "Une responsabilité claire.", "Des tests et déploiements automatisés.", "Des démonstrations communes régulières."] }] },
  { ...sourcePost(2), title: "Bonnes pratiques pour une infrastructure cloud", excerpt: "Un guide pratique pour construire des plateformes cloud sûres, fiables et attentives aux coûts.", category: "Cloud", readTime: "6 min de lecture", imageAlt: "Rangées de serveurs cloud dans un centre de données", body: [{ type: "p", text: "Le cloud apporte vitesse et flexibilité, mais nécessite des fondations claires pour éviter les coûts imprévus et les failles." }, { type: "h2", text: "Tout définir comme du code" }, { type: "p", text: "Décrivez l’infrastructure dans des fichiers versionnés pour rendre les environnements reproductibles et les changements vérifiables." }, { type: "h2", text: "Sécurité et coûts dès le départ" }, { type: "ul", items: ["Accorder le minimum de droits.", "Conserver les secrets hors du code.", "Identifier les ressources par équipe.", "Définir budgets et alertes."] }, { type: "quote", text: "La fiabilité se conçoit, elle ne s’ajoute pas après la première panne." }] },
];

const ar: Post[] = [
  { ...sourcePost(0), title: "استراتيجيات تحول رقمي تحقق نتائج فعلية", excerpt: "التحول يرتبط بالتركيز أكثر من ارتباطه بالتقنية. إليكم كيفية اختيار الأولويات وإظهار التقدم مبكراً.", category: "الاستراتيجية", readTime: "5 دقائق", imageAlt: "فريق يخطط لخارطة طريق للتحول الرقمي", body: [{ type: "p", text: "تبدأ برامج التحول الناجحة بقائمة قصيرة من مشكلات الأعمال، لا بقائمة طويلة من الأدوات. اتفقوا أولاً على النتائج المهمة." }, { type: "h2", text: "ابدؤوا بعملية واحدة" }, { type: "p", text: "اختاروا عملية مؤلمة وواضحة وقابلة للقياس، ثم صمموا أبسط نسخة رقمية تزيل أكبر عائق." }, { type: "quote", text: "أفضل خارطة طريق هي التي يرى الفريق تقدمها كل أسبوعين." }, { type: "h2", text: "اجعلوا التقدم مرئياً" }, { type: "ul", items: ["قدموا تحسينات صغيرة قابلة للاستخدام.", "راجعوا البرنامج مع المستخدمين في كل مرحلة.", "شاركوا الأولويات بين فرق الأعمال والتقنية.", "قيسوا التبني وليس التسليم فقط."] }] },
  { ...sourcePost(1), title: "كيف تتوسع فرق أجايل دون أن تتباطأ", excerpt: "إضافة الأشخاص لا تعني زيادة السرعة تلقائياً. هذه الممارسات تحافظ على زخم الفرق المتنامية.", category: "أجايل", readTime: "4 دقائق", imageAlt: "فريق أجايل يراجع مهام دورة العمل", body: [{ type: "p", text: "تتحرك الفرق الصغيرة بسرعة لأن التواصل بسيط. ومع نمو الفريق يصبح التنسيق هو العمل الحقيقي." }, { type: "h2", text: "حافظوا على فرق صغيرة ومستقلة" }, { type: "p", text: "أنشئوا عدة فرق صغيرة، يملك كل منها جزءاً واضحاً من المنتج." }, { type: "quote", text: "وسعوا عدد الفرق، لا حجم كل فريق." }, { type: "ul", items: ["رؤية منتج واحدة.", "ملكية واضحة لكل جزء.", "اختبارات ونشر آليان.", "عروض مشتركة منتظمة."] }] },
  { ...sourcePost(2), title: "أفضل ممارسات البنية التحتية السحابية", excerpt: "دليل عملي لبناء منصات سحابية آمنة وموثوقة وواعية بالتكاليف منذ البداية.", category: "السحابة", readTime: "6 دقائق", imageAlt: "صفوف من خوادم الحوسبة السحابية", body: [{ type: "p", text: "تمنح السحابة الفرق السرعة والمرونة، لكن الأسس غير الواضحة قد تؤدي إلى تكاليف مفاجئة وثغرات أمنية." }, { type: "h2", text: "عرّفوا كل شيء ككود" }, { type: "p", text: "صفوا البنية التحتية في ملفات خاضعة لإدارة الإصدارات لتصبح البيئات قابلة للتكرار والتغييرات قابلة للمراجعة." }, { type: "h2", text: "الأمان والتكلفة منذ اليوم الأول" }, { type: "ul", items: ["امنحوا أقل الصلاحيات اللازمة.", "احفظوا الأسرار بعيداً عن الكود.", "صنفوا الموارد حسب الفريق والمشروع.", "حددوا الميزانيات والتنبيهات."] }, { type: "quote", text: "الموثوقية تُصمم منذ البداية ولا تُضاف بعد أول عطل." }] },
];

export const localizedPosts: Record<Locale, Post[]> = { en: posts, fr, ar };
