<?php return [
'nav.services'=>'Services','nav.work'=>'Work','nav.approach'=>'Approach','nav.blog'=>'Blog','nav.cta'=>'Discuss your project','lang.label'=>'English',
'meta.title'=>'DigitalSquad | Software Engineering & Consulting','meta.description'=>'Agile delivery and engineering excellence, focused on the outcomes that matter to your business.','error.title'=>"This page didn't load",'error.body'=>'Something went wrong on our side. Please try again in a moment.',
'hero.eyebrow'=>'Software engineering & consulting','hero.title'=>'Move faster. Create lasting value.','hero.body'=>'Agile delivery and engineering excellence, focused on the outcomes that matter to your business.','hero.secondary'=>'Explore our expertise','hero.watch'=>'Watch our presentation',
'refs'=>'Teams we have delivered software for','services.eyebrow'=>'Ways to work together','services.title'=>'The right support for your next step.','services.body'=>'Three clear ways to engage, depending on whether you need a product built, more capacity, or a clearer technical path.',
'impact.eyebrow'=>'Selected engagements','impact.title'=>'Our Impact and success stories','impact.body'=>'Digital products and transformation programmes delivered by DigitalSquad team members across industry, finance, and public services.','impact.team'=>'Team members involved',
'approach.eyebrow'=>'How we work','approach.title'=>'Clear priorities. Visible progress.','approach.body'=>'A simple way of working that keeps scope, collaboration, and delivery visible from the first conversation.',
'blog.from'=>'From the blog','blog.latest'=>'Latest articles','blog.all'=>'View all articles','blog.title'=>'Notes from the team','blog.body'=>'Practical articles on software engineering, delivery, and building better products.','blog.none'=>'No articles yet','blog.empty'=>'Our first articles are on the way. Check back soon.','blog.read'=>'Read article','blog.back'=>'All articles','blog.newer'=>'Newer','blog.older'=>'Older',
'contact.title'=>'Tell us about your project.','contact.body'=>"Share a few details about your goal or team need. We'll reply with questions and suggest a call.",'contact.name'=>'Name','contact.email'=>'Email','contact.company'=>'Company','contact.interest'=>'Area of interest','contact.need'=>'Project or team need','contact.select'=>'Select an option','contact.send'=>'Send message','contact.sending'=>'Sending…','required'=>'required','optional'=>'optional','contact.sent'=>"Message sent. We'll be in touch shortly.",'contact.check'=>'Please check the highlighted fields.',
'footer.explore'=>'Explore','footer.company'=>'Company','footer.careers'=>'Careers & internships','footer.contact'=>'Contact','footer.blurb'=>'Software engineering and consulting for teams building, improving, and scaling products.','footer.rights'=>'All rights reserved.','skip'=>'Skip to content','menu.open'=>'Open menu','menu.close'=>'Close menu','home'=>'Go home','notfound'=>'Page not found','notfound.body'=>"The page you're looking for doesn't exist or is no longer available.",
];
