<?php return [
'nav.services'=>'Services','nav.work'=>'Réalisations','nav.approach'=>'Approche','nav.blog'=>'Blog','nav.cta'=>'Parlons de votre projet','lang.label'=>'Français',
'hero.eyebrow'=>'Ingénierie logicielle & conseil','hero.title'=>'Avancez plus vite. Créez une valeur durable.','hero.body'=>'Livraison agile et excellence technique, centrées sur les résultats qui comptent pour votre entreprise.','hero.secondary'=>'Découvrir notre expertise','hero.watch'=>'Voir notre présentation',
'refs'=>'Des équipes pour lesquelles nous avons livré des logiciels','services.eyebrow'=>'Nos modes de collaboration','services.title'=>'Le bon accompagnement pour votre prochaine étape.','services.body'=>'Trois façons claires de collaborer : construire un produit, renforcer une équipe ou améliorer une plateforme.',
'impact.eyebrow'=>'Missions sélectionnées','impact.title'=>'Notre impact et nos réussites','impact.body'=>'Des produits numériques et programmes de transformation livrés par les membres de DigitalSquad dans l’industrie, la finance et les services publics.','impact.team'=>'Membres de l’équipe',
'approach.eyebrow'=>'Notre méthode','approach.title'=>'Des priorités claires. Des progrès visibles.','approach.body'=>'Une méthode simple qui rend le périmètre, la collaboration et la livraison visibles dès le premier échange.',
'blog.from'=>'Depuis le blog','blog.latest'=>'Derniers articles','blog.all'=>'Voir tous les articles','blog.title'=>'Les notes de l’équipe','blog.body'=>'Des articles pratiques sur l’ingénierie logicielle, la livraison et la création de meilleurs produits.','blog.none'=>'Aucun article','blog.empty'=>'Nos premiers articles arrivent bientôt.','blog.read'=>'Lire l’article','blog.back'=>'Tous les articles','blog.newer'=>'Plus récents','blog.older'=>'Plus anciens',
'contact.title'=>'Parlez-nous de votre projet.','contact.body'=>'Partagez votre objectif ou le besoin de votre équipe. Nous vous répondrons avec quelques questions.','contact.name'=>'Nom','contact.email'=>'E-mail','contact.company'=>'Entreprise','contact.interest'=>'Domaine d’intérêt','contact.need'=>'Projet ou besoin de l’équipe','contact.select'=>'Choisir une option','contact.send'=>'Envoyer le message','contact.sending'=>'Envoi…','required'=>'obligatoire','optional'=>'facultatif','contact.sent'=>'Message envoyé. Nous vous répondrons prochainement.','contact.check'=>'Veuillez vérifier les champs indiqués.',
'footer.explore'=>'Explorer','footer.company'=>'Entreprise','footer.careers'=>'Carrières et stages','footer.contact'=>'Contact','footer.blurb'=>'Ingénierie logicielle et conseil pour les équipes qui créent, améliorent et font évoluer leurs produits.','footer.rights'=>'Tous droits réservés.','skip'=>'Aller au contenu','menu.open'=>'Ouvrir le menu','menu.close'=>'Fermer le menu','home'=>'Accueil','notfound'=>'Page introuvable','notfound.body'=>'La page demandée n’existe pas ou n’est plus disponible.',
];
